In [1]:
!pip install numpy


[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

## create array using numpy
## create a 1D : 1 Dimentional array
arry1 = np.array([1,2,3,4,5])
print(arry1)
print(type(arry1))
print(arry1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
## 2 Dimentional array
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)  ## 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [13]:
## convert 1D to 2D array
np.arange(0,10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [15]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
## Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
## Numpy vectorized operation

ar1 = np.array([1,2,3,4,5])
ar2 = np.array([10,20,30,40,50])
# Element wise addition
print("Addition : ", ar1 + ar2)

Addition :  [11 22 33 44 55]


In [25]:
## Universal fn
arr = np.array([2,3,4,5])
## square root
print(np.sqrt(arr))


[1.41421356 1.73205081 2.         2.23606798]


In [28]:
## arrray slicing and indexing
arr = np.array([[1,2,3,4], [6,7,8,9], [10,11,12,13]])
print(arr)

[[ 1  2  3  4]
 [ 6  7  8  9]
 [10 11 12 13]]


In [30]:
arr[0][0]

np.int64(1)

In [34]:
arr[1:, 2:]   ## 1: take all starting from 2nd column [column:, row:]

array([[ 8,  9],
       [12, 13]])

In [39]:
arr[1:] = 100
print(arr)
arr[1] = 120
print(arr)

[[  1   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]
[[  1   2   3   4]
 [120 120 120 120]
 [100 100 100 100]]


In [46]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

#mean
mean = np.mean(data)
print(mean)

#median 
print(np.median(data))

# Standard deviation
print(np.std(data))

#variance
print(np.var(data))

5.5
5.5
2.8722813232690143
8.25


In [51]:
## Logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])
data >5
data[data>5]
data [(data >5) & (data<9)]

array([6, 7, 8])